#Usamos una imagen de Node.js para construir el frontend
FROM node:20-alpine

# Establecer el directorio de trabajo
WORKDIR /usr/src/app

# Copiar los archivos del proyecto
COPY . .

# Instalar dependencias
RUN npm install

# Exponer el puerto en el que correrá la aplicación Nuxt
EXPOSE 3000

# Comando por defecto para ejecutar la aplicación en modo producción
CMD ["npm", "run", "dev"]
