# Usamos una imagen de Node.js para construir el frontend
FROM node:20-alpine

# Establecer el directorio de trabajo
WORKDIR /usr/src/app

# Copiar los archivos de package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
# RUN npm install

# Copiar el resto de los archivos del proyecto
COPY . .

# Exponer el puerto en el que correrá la aplicación Nuxt
EXPOSE 3000

# Comando por defecto para ejecutar la aplicación en modo desarrollo
CMD ["npm install && npm run dev"]


